name: Release

on:
  workflow_run:
    workflows: ['Build and Test']
    branches: [main]
    types: [completed]

jobs:
  release:
    name: Semantic release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-workflow-run-wait@v1 # only if 'Build and Test' succeeds

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          branch: main
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      released: ${{ steps.semantic.outputs.new_release_published }}
      released_version: ${{ steps.semantic.outputs.new_release_version }}

  build-and-push-image:
    needs: release
    if: needs.release.outputs.released == 'true'

    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          tags: |
            ghcr.io/turnstileio/nuts:latest
            ghcr.io/turnstileio/nuts:v${{ needs.release.outputs.released_version }}
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
